services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d
      - ./init.sh:/etc/localstack/init/ready.d/init.sh
  aws:
    build:
      context: .
      dockerfile: AWS/Dockerfile
    depends_on:
      - localstack
    environment:
      - AWS_SERVICE_URL=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=fake
      - AWS_SECRET_ACCESS_KEY=fake
    command: bash -c "sleep 10 && dotnet run --project /app/src/SqsSnsApp.csproj"